const vocabWords = [
    // Personality / Descriptions
    { french: "Romantique", english: "Romantic", accuracy: 0.0 },
    { french: "Drole", english: "Funny", accuracy: 0.0 },
    { french: "Marrant", english: "Funny", accuracy: 0.0 },
    { french: "Timide", english: "Shy", accuracy: 0.0 },
    { french: "Maladroite", english: "Awkward", accuracy: 0.0 },

    // Polite expressions
    { french: "C'est gentil de", english: "It's nice to", accuracy: 0.0 },
    { french: "Merci de", english: "Thank you for", accuracy: 0.0 },
    { french: "Oui, d'accord", english: "Yes, okay", accuracy: 0.0 },
    { french: "Tres bien", english: "Very good", accuracy: 0.0 },
    { french: "Bien sur", english: "Of course", accuracy: 0.0 },
    { french: "Hors de question", english: "Out of the question", accuracy: 0.0 },
    { french: "Pas question", english: "No question", accuracy: 0.0 },
    { french: "Desole, mais", english: "Sorry, but...", accuracy: 0.0 },

    // Friends
    { french: "Le meilleur ami", english: "The best friend", accuracy: 0.0 },
    { french: "Un ami virtuel", english: "A virtuel friend", accuracy: 0.0 },
    { french: "Un copain du sport", english: "A sport friend", accuracy: 0.0 },
    { french: "Un ami d'enfance", english: "A childhood friend", accuracy: 0.0 },
    { french: "S'entendre bien avec quelqu'un", english: "To get along well with someone", accuracy: 0.0 },
    { french: "Aimer bien quelqu'un", english: "To like someone", accuracy: 0.0 },
    { french: "Se disputer avec quelqu'un", english: "To argue with someone", accuracy: 0.0 },
    { french: "Avoir grandi avec quelqu'un", english: "To have grown up with someone", accuracy: 0.0 },
    { french: "Se voir tous les jours", english: "To see each other everyday", accuracy: 0.0 },
    { french: "Etres inseparables", english: "To be inseperable", accuracy: 0.0 },
    { french: "Etre comme des frères / soeurs", english: "To be like brothers / sisters", accuracy: 0.0 },

    // Future / Time
    { french: "Peut-etre", english: "Maybe", accuracy: 0.0 },
    { french: "Cest sur", english: "It's sure", accuracy: 0.0 },
    { french: "Cest impossible", english: "It's impossible", accuracy: 0.0 },
    { french: "Demain", english: "Tomorrow", accuracy: 0.0 },
    { french: "Bientot", english: "Soon", accuracy: 0.0 },
    { french: "Un jour", english: "One day", accuracy: 0.0 },
    { french: "Dans 50 ans", english: "In 50 years", accuracy: 0.0 },
    { french: "En 2040", english: "In 2040", accuracy: 0.0 },
    { french: "Une année", english: "A year", accuracy: 0.0 },
    { french: "Un siècle", english: "A century", accuracy: 0.0 },
    { french: "Un millénaire", english: "A thousand years", accuracy: 0.0 },
    { french: "Une décennie", english: "A decade", accuracy: 0.0 },

    // House / Furniture
    { french: "l'Armoire", english: "The closet", accuracy: 0.0 },
    { french: "Le réfrigérateur", english: "The refridgerator", accuracy: 0.0 },
    { french: "Le chauffage", english: "The heater", accuracy: 0.0 },
    { french: "Le miroir", english: "The mirror", accuracy: 0.0 },
    { french: "Le lit", english: "The bed", accuracy: 0.0 },
    { french: "La machine a laver", english: "The washing machine", accuracy: 0.0 },
    { french: "La television", english: "The television", accuracy: 0.0 },
    { french: "La chambre", english: "The room", accuracy: 0.0 },
    { french: "Le salon", english: "The living room", accuracy: 0.0 },
    { french: "La cuisine", english: "The kitchen", accuracy: 0.0 },
    { french: "La salle de bain", english: "The bathroom", accuracy: 0.0 },
    { french: "Le toit", english: "The roof", accuracy: 0.0 },
    { french: "Les plantes", english: "The plants", accuracy: 0.0 },
    { french: "Les meubles", english: "The furniture", accuracy: 0.0 },
    { french: "Les pieces", english: "The rooms", accuracy: 0.0 },
    { french: "Les murs", english: "The walls", accuracy: 0.0 },

    // Technology
    { french: "Automatise", english: "Automated", accuracy: 0.0 },
    { french: "Intelligent", english: "Intelligent", accuracy: 0.0 },
    { french: "Une assistance vocale", english: "A vocal assistant", accuracy: 0.0 },
    { french: "En ligne", english: "Online", accuracy: 0.0 },
    { french: "Connecte", english: "Connected", accuracy: 0.0 },
    { french: "Une application mobile", english: "A mobile application", accuracy: 0.0 },
    { french: "Un smartphone", english: "A smartphone", accuracy: 0.0 },

    // Travel / Activities
    { french: "Voyager", english: "To travel", accuracy: 0.0 },
    { french: "En voiture", english: "By car", accuracy: 0.0 },
    { french: "En avion", english: "By plane", accuracy: 0.0 },
    { french: "En train", english: "By train", accuracy: 0.0 },
    { french: "Se baigner", english: "To bathe", accuracy: 0.0 },
    { french: "Faire du vélo", english: "To go biking", accuracy: 0.0 },
    { french: "Faire du kayak", english: "To go kayaking", accuracy: 0.0 },
    { french: "Faire du ski", english: "To go skiing", accuracy: 0.0 },
    { french: "Faire du surf", english: "To go surfing", accuracy: 0.0 },
    { french: "Faire des randonnées", english: "To go hiking", accuracy: 0.0 },
    { french: "Faire de la plonge", english: "To go diving", accuracy: 0.0 },
    { french: "Visiter un musée", english: "To visit a museum", accuracy: 0.0 },
    { french: "Visiter une grotte", english: "To visit a cave", accuracy: 0.0 },
    { french: "Faire un pique-nique", english: "To do a picnic", accuracy: 0.0 },
    { french: "Se promener", english: "To take a walk", accuracy: 0.0 },

    // Places / Landmarks
    { french: "Un pont", english: "A bridge", accuracy: 0.0 },
    { french: "Une pyramide", english: "A pyramid", accuracy: 0.0 },
    { french: "Un restaurant", english: "A restaurant", accuracy: 0.0 },
    { french: "Une mosquee", english: "A mosque", accuracy: 0.0 },
    { french: "Une église", english: "A church", accuracy: 0.0 },
    { french: "Une cathédrale", english: "A Cathedral", accuracy: 0.0 },
    { french: "Une porte", english: "A door", accuracy: 0.0 },
    { french: "Un musée", english: "A museum", accuracy: 0.0 },
    { french: "Une montagne", english: "A mountain", accuracy: 0.0 },
    { french: "Une statue", english: "A statue", accuracy: 0.0 },
    { french: "Un port", english: "A port", accuracy: 0.0 },

    // Reactions / Opinions
    { french: "J'ai adore", english: "I loved it", accuracy: 0.0 },
    { french: "Ca ta plu?", english: "Did you like it?", accuracy: 0.0 },
    { french: "Ca ma beaucoup plu !", english: "I liked it a lot", accuracy: 0.0 },
    { french: "C'est genial", english: "It's awesome", accuracy: 0.0 },
    { french: "C'etait super interessant", english: "It was super interesting", accuracy: 0.0 },
    { french: "C'est chouette", english: "It's awesome", accuracy: 0.0 },
    { french: "C'est connue pour", english: "It's known for", accuracy: 0.0 },
    { french: "C'est se trouve", english: "It's found", accuracy: 0.0 },
    { french: "Dans cette ville, il y a...", english: "In this city, there is...", accuracy: 0.0 },
    { french: "C'est une ville qui...", english: "It's a city that...", accuracy: 0.0 },

    // Time expressions
    { french: "La semaine derniere", english: "Last week", accuracy: 0.0 },
    { french: "Le mois dernier", english: "Last month", accuracy: 0.0 },
    { french: "L'annee prochaine", english: "Next year", accuracy: 0.0 },
    { french: "Le week-end prochain", english: "Next weekend", accuracy: 0.0 },
    { french: "Après-demain", english: "After tomorrow", accuracy: 0.0 },
    { french: "Hier", english: "Yesterday", accuracy: 0.0 },
    { french: "avant-hier", english: "Before yesterday", accuracy: 0.0 },
    { french: "Le premier jour", english: "The first day", accuracy: 0.0 },
    { french: "Le jour suivant", english: "The next day", accuracy: 0.0 },
    { french: "D'abord", english: "Firstly", accuracy: 0.0 },
    { french: "Ensuite", english: "Then", accuracy: 0.0 },
    { french: "Finalement", english: "Finally", accuracy: 0.0 },

    // Cooking
    { french: "Couper", english: "To cut", accuracy: 0.0 },
    { french: "Ajouter", english: "To add", accuracy: 0.0 },
    { french: "Verser", english: "To pour", accuracy: 0.0 },
    { french: "Melanger", english: "To mix", accuracy: 0.0 },
    { french: "Sortir du four", english: "To take out of the oven", accuracy: 0.0 },
    { french: "Cuire", english: "To cook", accuracy: 0.0 },

    // Food
    { french: "La salade verte", english: "Green salad", accuracy: 0.0 },
    { french: "Les carottes", english: "Carrots", accuracy: 0.0 },
    { french: "Les tomates", english: "Tomatos", accuracy: 0.0 },
    { french: "Les pommes", english: "Apples", accuracy: 0.0 },
    { french: "Les ananas", english: "Pineapples", accuracy: 0.0 },
    { french: "Le poulet", english: "Chicken", accuracy: 0.0 },
    { french: "Le boeuf", english: "Beef", accuracy: 0.0 },
    { french: "Le fromage", english: "Cheese", accuracy: 0.0 },
    { french: "Le lait", english: "Milk", accuracy: 0.0 },
    { french: "Le yaourt", english: "Yogurt", accuracy: 0.0 },
    { french: "Un kilo", english: "A kilo", accuracy: 0.0 },
    { french: "100 grammes", english: "100 grams", accuracy: 0.0 },
    { french: "Un pot", english: "A pot", accuracy: 0.0 },
    { french: "Une bouteille", english: "A bottle", accuracy: 0.0 },
    { french: "Une boite", english: "A box", accuracy: 0.0 },
    { french: "Une tranche", english: "A slice", accuracy: 0.0 },
    { french: "Le riz", english: "Rice", accuracy: 0.0 },
    { french: "Le pain", english: "Bread", accuracy: 0.0 },
    { french: "Les pates", english: "Pasta", accuracy: 0.0 },
    { french: "Les pommes de terre", english: "Potatos", accuracy: 0.0 },

    // Dietary
    { french: "Je suis allergique au…", english: "I am allergic to...", accuracy: 0.0 },
    { french: "Je suis intolerant au…", english: "I am interlorant to...", accuracy: 0.0 },
    { french: "Je ne peux pas manger de..", english: "I can not eat...", accuracy: 0.0 },

    // Louis Braille Speech
    { french: "est ne", english: "is born", accuracy: 0.0 },
    { french: "avant", english: "before", accuracy: 0.0 },
    { french: "jeune", english: "young", accuracy: 0.0 },
    { french: "aveugle", english: "blind", accuracy: 0.0 },
    { french: "devenir", english: "to become", accuracy: 0.0 },
    { french: "et donc", english: "and so", accuracy: 0.0 },
    { french: "plus tard", english: "later", accuracy: 0.0 },
    { french: "est mort", english: "is dead", accuracy: 0.0 },
    { french: "Le meme", english: "The same", accuracy: 0.0 },
    { french: "Une chose", english: "A thing", accuracy: 0.0 },
];
