// Vocabulary Words List
// Format: { french: "french word", english: "english translation", accuracy: 0.0 }
// Add new words by copying the format below

const vocabWords = [
    // Personality / Descriptions
    { french: "Romantique", english: "Romantic", accuracy: 0.0 },
    { french: "Drole", english: "Funny", accuracy: 0.0 },
    { french: "Marrant", english: "Funny", accuracy: 0.0 },
    { french: "Timide", english: "Shy", accuracy: 0.0 },
    { french: "Maladroite", english: "Awkward", accuracy: 0.0 },

    // Polite expressions
    { french: "C'est gentil de", english: "It's nice to", accuracy: 0.0 },
    { french: "Merci de", english: "Thank you for", accuracy: 0.0 },
    { french: "Oui, d'accord", english: "Yes, okay", accuracy: 0.0 },
    { french: "Tres bien", english: "Very good", accuracy: 0.0 },
    { french: "Bien sur", english: "Of course", accuracy: 0.0 },
    { french: "Hors de question", english: "TODO", accuracy: 0.0 },
    { french: "Pas question", english: "TODO", accuracy: 0.0 },
    { french: "Desole, mais", english: "TODO", accuracy: 0.0 },

    // Friends
    { french: "Le meilleur ami", english: "TODO", accuracy: 0.0 },
    { french: "Un ami virtuel", english: "TODO", accuracy: 0.0 },
    { french: "Un copain du sport", english: "TODO", accuracy: 0.0 },
    { french: "Un ami d'enfance", english: "TODO", accuracy: 0.0 },
    { french: "S'entendre bien avec quelqu'un", english: "TODO", accuracy: 0.0 },
    { french: "Aimer bien quelqu'un", english: "TODO", accuracy: 0.0 },
    { french: "Se disputer avec quelqu'un", english: "TODO", accuracy: 0.0 },
    { french: "Avoir grandi avec quelqu'un", english: "TODO", accuracy: 0.0 },
    { french: "Se voir tous les jours", english: "TODO", accuracy: 0.0 },
    { french: "Etres inseparables", english: "TODO", accuracy: 0.0 },
    { french: "Etre comme des frères", english: "TODO", accuracy: 0.0 },

    // Future / Time
    { french: "Peutetre", english: "TODO", accuracy: 0.0 },
    { french: "Cest sur", english: "TODO", accuracy: 0.0 },
    { french: "Cest impossible", english: "TODO", accuracy: 0.0 },
    { french: "Demain", english: "TODO", accuracy: 0.0 },
    { french: "Bientot", english: "TODO", accuracy: 0.0 },
    { french: "Un jour", english: "TODO", accuracy: 0.0 },
    { french: "Dans 50 ans", english: "TODO", accuracy: 0.0 },
    { french: "En 2040", english: "TODO", accuracy: 0.0 },
    { french: "Une année", english: "TODO", accuracy: 0.0 },
    { french: "Un siècle", english: "TODO", accuracy: 0.0 },
    { french: "Un millénaire", english: "TODO", accuracy: 0.0 },
    { french: "Une décennie", english: "TODO", accuracy: 0.0 },

    // House / Furniture
    { french: "l'Armoire", english: "TODO", accuracy: 0.0 },
    { french: "Le réfrigérateur", english: "TODO", accuracy: 0.0 },
    { french: "Le chauffage", english: "TODO", accuracy: 0.0 },
    { french: "Le miroir", english: "TODO", accuracy: 0.0 },
    { french: "Le lit", english: "TODO", accuracy: 0.0 },
    { french: "La machine a laver", english: "TODO", accuracy: 0.0 },
    { french: "La television", english: "TODO", accuracy: 0.0 },
    { french: "La chambre", english: "TODO", accuracy: 0.0 },
    { french: "Le salon", english: "TODO", accuracy: 0.0 },
    { french: "La cuisine", english: "TODO", accuracy: 0.0 },
    { french: "La salle de bain", english: "TODO", accuracy: 0.0 },
    { french: "Le toit", english: "TODO", accuracy: 0.0 },
    { french: "Les plantes", english: "TODO", accuracy: 0.0 },
    { french: "Les meubles", english: "TODO", accuracy: 0.0 },
    { french: "Les pieces", english: "TODO", accuracy: 0.0 },
    { french: "Les murs", english: "TODO", accuracy: 0.0 },

    // Technology
    { french: "Automatise", english: "TODO", accuracy: 0.0 },
    { french: "Intelligent", english: "TODO", accuracy: 0.0 },
    { french: "Une assistance vocale", english: "TODO", accuracy: 0.0 },
    { french: "En ligne", english: "TODO", accuracy: 0.0 },
    { french: "Connecte", english: "TODO", accuracy: 0.0 },
    { french: "Une application mobile", english: "TODO", accuracy: 0.0 },
    { french: "Un smartphone", english: "TODO", accuracy: 0.0 },

    // Travel / Activities
    { french: "Voyager", english: "TODO", accuracy: 0.0 },
    { french: "En voiture", english: "TODO", accuracy: 0.0 },
    { french: "En avion", english: "TODO", accuracy: 0.0 },
    { french: "En train", english: "TODO", accuracy: 0.0 },
    { french: "Se baigner", english: "TODO", accuracy: 0.0 },
    { french: "Faire du vélo", english: "TODO", accuracy: 0.0 },
    { french: "Faire du kayak", english: "TODO", accuracy: 0.0 },
    { french: "Faire du ski", english: "TODO", accuracy: 0.0 },
    { french: "Faire du surf", english: "TODO", accuracy: 0.0 },
    { french: "Faire des raquettes", english: "TODO", accuracy: 0.0 },
    { french: "Faire des randonnées", english: "TODO", accuracy: 0.0 },
    { french: "Faire de la plunge", english: "TODO", accuracy: 0.0 },
    { french: "Visiter un musée", english: "TODO", accuracy: 0.0 },
    { french: "Visiter une grotte", english: "TODO", accuracy: 0.0 },
    { french: "Faire un pique-nique", english: "TODO", accuracy: 0.0 },
    { french: "Se promener", english: "TODO", accuracy: 0.0 },

    // Places / Landmarks
    { french: "Un pont", english: "TODO", accuracy: 0.0 },
    { french: "Une pyramide", english: "TODO", accuracy: 0.0 },
    { french: "Un restaurant", english: "TODO", accuracy: 0.0 },
    { french: "Une mosquee", english: "TODO", accuracy: 0.0 },
    { french: "Une église", english: "TODO", accuracy: 0.0 },
    { french: "Une cathédrale", english: "TODO", accuracy: 0.0 },
    { french: "Une porte", english: "TODO", accuracy: 0.0 },
    { french: "Un musée", english: "TODO", accuracy: 0.0 },
    { french: "Une montagne", english: "TODO", accuracy: 0.0 },
    { french: "Une medina", english: "TODO", accuracy: 0.0 },
    { french: "Une citadelle", english: "TODO", accuracy: 0.0 },
    { french: "Une statue", english: "TODO", accuracy: 0.0 },
    { french: "Un port", english: "TODO", accuracy: 0.0 },

    // Reactions / Opinions
    { french: "Jai adore", english: "TODO", accuracy: 0.0 },
    { french: "Ca ta plu?", english: "TODO", accuracy: 0.0 },
    { french: "Ca ma beaucoup plu !", english: "TODO", accuracy: 0.0 },
    { french: "Cest genial", english: "TODO", accuracy: 0.0 },
    { french: "Certain super interessant", english: "TODO", accuracy: 0.0 },
    { french: "Cest chouette", english: "TODO", accuracy: 0.0 },
    { french: "Elle est connue pour", english: "TODO", accuracy: 0.0 },
    { french: "Elle se trouve", english: "TODO", accuracy: 0.0 },
    { french: "Dans cette ville, il y a", english: "TODO", accuracy: 0.0 },
    { french: "Cest une ville qui", english: "TODO", accuracy: 0.0 },

    // Time expressions
    { french: "La semaine derniere", english: "TODO", accuracy: 0.0 },
    { french: "Le mois dernier", english: "TODO", accuracy: 0.0 },
    { french: "lannee prochaine", english: "TODO", accuracy: 0.0 },
    { french: "Le week-end prochain", english: "TODO", accuracy: 0.0 },
    { french: "Après-demain", english: "TODO", accuracy: 0.0 },
    { french: "Hier", english: "TODO", accuracy: 0.0 },
    { french: "avant-hier", english: "TODO", accuracy: 0.0 },
    { french: "Le premier jour", english: "TODO", accuracy: 0.0 },
    { french: "Le jour suivant", english: "TODO", accuracy: 0.0 },
    { french: "Dabord", english: "TODO", accuracy: 0.0 },
    { french: "Ensuite", english: "TODO", accuracy: 0.0 },
    { french: "Finalement", english: "TODO", accuracy: 0.0 },

    // Cooking
    { french: "Couper", english: "TODO", accuracy: 0.0 },
    { french: "Plucker", english: "TODO", accuracy: 0.0 },
    { french: "Ajouter", english: "TODO", accuracy: 0.0 },
    { french: "Verser", english: "TODO", accuracy: 0.0 },
    { french: "Saupoudrer", english: "TODO", accuracy: 0.0 },
    { french: "Melanger", english: "TODO", accuracy: 0.0 },
    { french: "Sortir du four", english: "TODO", accuracy: 0.0 },
    { french: "Cuire", english: "TODO", accuracy: 0.0 },

    // Food
    { french: "La salade verte", english: "TODO", accuracy: 0.0 },
    { french: "Les carottes", english: "TODO", accuracy: 0.0 },
    { french: "Les tomates", english: "TODO", accuracy: 0.0 },
    { french: "Les pommes", english: "TODO", accuracy: 0.0 },
    { french: "Les ananas", english: "TODO", accuracy: 0.0 },
    { french: "Le poulet", english: "TODO", accuracy: 0.0 },
    { french: "Le boeuf", english: "TODO", accuracy: 0.0 },
    { french: "Le fromage", english: "TODO", accuracy: 0.0 },
    { french: "Le lait", english: "TODO", accuracy: 0.0 },
    { french: "Le yaourt", english: "TODO", accuracy: 0.0 },
    { french: "Un kilo", english: "TODO", accuracy: 0.0 },
    { french: "100 grammes", english: "TODO", accuracy: 0.0 },
    { french: "Un pot", english: "TODO", accuracy: 0.0 },
    { french: "Une bouteille", english: "TODO", accuracy: 0.0 },
    { french: "Une boite", english: "TODO", accuracy: 0.0 },
    { french: "Une tranche", english: "TODO", accuracy: 0.0 },
    { french: "Le riz", english: "TODO", accuracy: 0.0 },
    { french: "Le pain", english: "TODO", accuracy: 0.0 },
    { french: "Les pates", english: "TODO", accuracy: 0.0 },
    { french: "Les pommes de terre", english: "TODO", accuracy: 0.0 },

    // Dietary
    { french: "Je suis allergique au…", english: "TODO", accuracy: 0.0 },
    { french: "Je suis intolerant au…", english: "TODO", accuracy: 0.0 },
    { french: "Je ne peux pas manger de..", english: "TODO", accuracy: 0.0 },
];
